### ISSUE TITLE
No custom Pod provider possible

### ISSUE THREAD

**Issue by Vinnl** [empathyco/oh-my-pod#2]
Cool project! However, I have a locally running Pod server with which I usually test new services - but since Oh My Pod! only allows me to choose between solid.community and inrupt.net, I am unable to use it :( This goes somewhat against the idea of being able to choose to store your data wherever you want. Would it be possible to add support for signing in with a different Pod provider as well?

**Comment by astrd** [comment]
Yes I will work on that. It just wasnt a priority. Our app is still in development but we wanted to show it in the solid world event. Thank you for your feedback

**Comment by alexcorvis84** [comment]
@astrd regarding to this issue. Please check this post where @Vinnl posted some tips to develop this. 

https://forum.solidproject.org/t/custom-login-user-interface/2478

**Comment by astrd** [comment]
hello this issue is now solved! You can check the new implementation here https://ohmypod.netlify.com/
