### ISSUE TITLE
Responsive?

### ISSUE THREAD

**Issue by scenaristeur** [empathyco/oh-my-pod#3]
Could it be responsive ? 
Here is what I get on my mobile device
![Screenshot_20200414-100625_Chrome](https://user-images.githubusercontent.com/4020744/79201086-c9abc500-7e37-11ea-9db1-268b9476b024.jpg)
![Screenshot_20200414-100528_Chrome](https://user-images.githubusercontent.com/4020744/79201090-ca445b80-7e37-11ea-9d4a-00c68ac0acfa.jpg)
![Screenshot_20200414-100540_Chrome](https://user-images.githubusercontent.com/4020744/79201092-cadcf200-7e37-11ea-9bc2-848cc50191d9.jpg)
![Screenshot_20200414-100458_Chrome](https://user-images.githubusercontent.com/4020744/79201094-cb758880-7e37-11ea-92a5-979aa074751e.jpg)

**Comment by astrd** [comment]
Yes i'm working on it too. I hope it will be available at the end of the month

**Comment by alexcorvis84** [comment]
@scenaristeur thanks a lot for the feedback!

**Comment by astrd** [comment]
Responsive design has been applied
